### ISSUE TITLE
In the generated JSON for a resource, some fields are erroneously named using UUIDs

### ISSUE THREAD

**Issue by rdshankar** [metadatacenter/cedar-project#191] opened 2016-10-03 22:02 UTC
For example, in the GEO template, the Sample Organism has name...
   "e6c53aa5-3ec7-4d9c-a1e0-176a3f542c78"
instead of something like 
   gEOSampleOrganism

**Comment by martinjoconnor** [comment] 2016-10-04 16:40
Duplicate of metadatacenter/cedar-template-editor#531.

**Closed** 2016-10-04 16:40 UTC
Labels: bug
