### ISSUE TITLE
import_mode=true returns error 500

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-project#525] opened 2017-07-19 22:12 UTC
It happened when making a POST to the following URL: https://resource.metadatacenter.net/templates?import_mode=true

The POST body is available at https://docs.google.com/document/d/1-zPTFCZnCx5R-AQq9_51CN8ZEuNdoko52RBjhVEKvAQ/edit?usp=sharing

**Comment by martinjoconnor** [comment] 2017-08-23 21:06
Duplicate of https://github.com/metadatacenter/cedar-resource-server/issues/33

**Closed** 2017-08-23 21:07 UTC
Labels: bug, duplicate
