### ISSUE TITLE
can't edit inserted element

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#137] opened 2016-09-15 06:01 UTC
I tried inserting the element I created, URL below, into a template. (A) I couldn't edit the name or any other field. (B) Double-clicking on the editable fields produced random open-close behaviors, sometimes closing value box, sometimes hiding field type, sometimes hiding a whole field.

https://cedar.metadatacenter.net/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F1d427c28-3d67-44e9-a6a0-bfdedaf3aa89 should get to it ("BioCADDIE Dataset Ish" is the name)

**Comment by graybeal** [comment] 2016-09-15 06:03
Resulting JSON template was 

{
  "@id": "https://repo.metadatacenter.net/templates/6c96dcce-5466-4917-9063-453d53dae37a",
  "@type": "https://schema.metadatacenter.org/core/Template",
  "@context": {
    "pav": "http://purl.org/pav/",
    "oslc": "http://open-services.net/ns/core#",
    "schema": "http://schema.org/"
  },
  "type": "object",
  "title": "Test template schema",
  "description": "Test template schema autogenerated by the CEDAR Template Editor",
  "_ui": {
    "title": "test",
    "description": "test really",
    "pages": [],
    "order": [
      "bioCADDIEDatasetIsh",
      "94e8e2ad-e76a-4d1e-8bbf-4a70568fee7e"
    ]
  },
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "pav": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://purl.org/pav/"
          ]
        },
        "schema": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://schema.org/"
          ]
        },
        "oslc": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://open-services.net/ns/core#"
          ]
        },
        "bioCADDIEDatasetIsh": {
          "enum": [
            "https://schema.metadatacenter.net/properties/bioCADDIEDatasetIsh"
          ]
        },
        "94e8e2ad-e76a-4d1e-8bbf-4a70568fee7e": {
          "enum": [
            "https://schema.metadatacenter.net/properties/94e8e2ad-e76a-4d1e-8bbf-4a70568fee7e"
          ]
        }
      },
      "patternProperties": {
        "^(?!pav)(?!schema)(?!oslc)[a-zA-Z][a-zA-Z0-9]*$": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "pav",
        "schema",
        "oslc",
        "bioCADDIEDatasetIsh",
        "94e8e2ad-e76a-4d1e-8bbf-4a70568fee7e"
      ],
      "additionalProperties": false
    },
    "@id": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "@type": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "uniqueItems": true
        }
      ]
    },
    "schema:isBasedOn": {
      "type": "string",
      "format": "uri"
    },
    "schema:name": {
      "type": "string",
      "minLength": 1
    },
    "schema:description": {
      "type": "string"
    },
    "pav:createdOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "pav:createdBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:lastUpdatedOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "oslc:modifiedBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "bioCADDIEDatasetIsh": {
      "@id": "https://repo.metadatacenter.net/template-elements/2ddd6ffe-3db9-482c-aeb8-796767e9b0a1",
      "@type": "https://schema.metadatacenter.org/core/TemplateElement",
      "@context": {
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#"
      },
      "type": "object",
      "title": "Biocaddie dataset (ish) element schema",
      "description": "Biocaddie dataset (ish) element schema autogenerated by the CEDAR Template Editor",
      "_ui": {
        "title": "BioCADDIE Dataset Ish",
        "description": "Dataset components used by BioCADDIE",
        "order": [
          "resolvableDatasetID",
          "dataType"
        ]
      },
      "properties": {
        "@context": {
          "type": "object",
          "properties": {
            "pav": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://purl.org/pav/"
              ]
            },
            "oslc": {
              "type": "string",
              "format": "uri",
              "enum": [
                "http://open-services.net/ns/core#"
              ]
            },
            "resolvableDatasetID": {
              "enum": [
                "https://schema.metadatacenter.net/properties/resolvableDatasetID"
              ]
            },
            "datasetTitle": {
              "enum": [
                "https://schema.metadatacenter.net/properties/datasetTitle"
              ]
            },
            "dataType": {
              "enum": [
                "https://schema.metadatacenter.net/properties/dataType"
              ]
            }
          },
          "patternProperties": {
            "^(?!pav)(?!schema)(?!oslc)[a-zA-Z][a-zA-Z0-9]*$": {
              "type": "string",
              "format": "uri"
            }
          },
          "required": [
            "resolvableDatasetID",
            "datasetTitle",
            "dataType"
          ],
          "additionalProperties": false
        },
        "@id": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "resolvableDatasetID": {
          "@type": "https://schema.metadatacenter.org/core/TemplateField",
          "@context": {
            "schema": "http://schema.org/",
            "pav": "http://purl.org/pav/",
            "oslc": "http://open-services.net/ns/core#"
          },
          "type": "object",
          "title": "Resolvable dataset id field schema",
          "description": "Resolvable dataset id field schema autogenerated by the CEDAR Template Editor",
          "_ui": {
            "title": "Resolvable Dataset ID",
            "description": "",
            "inputType": "textfield"
          },
          "_valueConstraints": {
            "requiredValue": true
          },
          "properties": {
            "@id": {
              "type": [
                "string",
                "null"
              ],
              "format": "uri"
            },
            "@type": {
              "oneOf": [
                {
                  "type": "string",
                  "format": "uri"
                },
                {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "format": "uri"
                  },
                  "uniqueItems": true
                }
              ]
            },
            "@value": {
              "type": [
                "string",
                "null"
              ]
            },
            "pav:createdOn": {
              "type": [
                "string",
                "null"
              ],
              "format": "date-time"
            },
            "pav:createdBy": {
              "type": [
                "string",
                "null"
              ],
              "format": "uri"
            },
            "pav:lastUpdatedOn": {
              "type": [
                "string",
                "null"
              ],
              "format": "date-time"
            },
            "oslc:modifiedBy": {
              "type": [
                "string",
                "null"
              ],
              "format": "uri"
            },
            "_tmp": {}
          },
          "required": [
            "@value"
          ],
          "pav:createdOn": "2016-09-14T22:00:46-0700",
          "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
          "pav:lastUpdatedOn": "2016-09-14T22:00:46-0700",
          "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
          "additionalProperties": false,
          "@id": "https://repo.metadatacenter.net/template-fields/71507660-0f94-4eca-88c2-7d4469f5f3a1",
          "$schema": "http://json-schema.org/draft-04/schema#"
        },
        "dataType": {
          "@type": "https://schema.metadatacenter.org/core/TemplateField",
          "@context": {
            "schema": "http://schema.org/",
            "pav": "http://purl.org/pav/",
            "oslc": "http://open-services.net/ns/core#"
          },
          "type": "object",
          "title": "Data type field schema",
          "description": "Data type field schema autogenerated by the CEDAR Template Editor",
          "_ui": {
            "title": "Data Type",
            "description": "What kind of data is represented in this dataset?",
            "inputType": "radio"
          },
          "_valueConstraints": {
            "requiredValue": false,
            "literals": [
              {
                "label": "Protein Structure"
              },
              {
                "label": "Physiological Signals"
              },
              {
                "label": "Morphology"
              },
              {
                "label": "Nucleotide Sequence"
              },
              {
                "label": "Phenotype"
              },
              {
                "label": "Clinical Trials"
              },
              {
                "label": "Proteomics Data"
              },
              {
                "label": "Gene Expression"
              },
              {
                "label": "Imaging Data"
              },
              {
                "label": "Unspecified"
              }
            ]
          },
          "properties": {
            "@id": {
              "type": [
                "string",
                "null"
              ],
              "format": "uri"
            },
            "@type": {
              "oneOf": [
                {
                  "type": "string",
                  "format": "uri"
                },
                {
                  "type": "array",
                  "minItems": 1,
                  "items": {
                    "type": "string",
                    "format": "uri"
                  },
                  "uniqueItems": true
                }
              ]
            },
            "@value": {
              "type": [
                "array",
                "null"
              ]
            },
            "pav:createdOn": {
              "type": [
                "string",
                "null"
              ],
              "format": "date-time"
            },
            "pav:createdBy": {
              "type": [
                "string",
                "null"
              ],
              "format": "uri"
            },
            "pav:lastUpdatedOn": {
              "type": [
                "string",
                "null"
              ],
              "format": "date-time"
            },
            "oslc:modifiedBy": {
              "type": [
                "string",
                "null"
              ],
              "format": "uri"
            },
            "_tmp": {}
          },
          "required": [
            "@value"
          ],
          "pav:createdOn": "2016-09-14T22:00:46-0700",
          "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
          "pav:lastUpdatedOn": "2016-09-14T22:00:46-0700",
          "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
          "additionalProperties": false,
          "@id": "https://repo.metadatacenter.net/template-fields/ce7bd634-c22c-4d4c-9c34-44d97fa60ff1",
          "$schema": "http://json-schema.org/draft-04/schema#"
        },
        "_tmp": {
          "state": "creating"
        }
      },
      "required": [],
      "pav:createdOn": "2016-09-14T15:50:15-0700",
      "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "pav:lastUpdatedOn": "2016-09-14T22:56:47-0700",
      "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "additionalProperties": false,
      "$schema": "http://json-schema.org/draft-04/schema#",
      "_tmp": {
        "domId": "id05949536730710732"
      }
    },
    "94e8e2ad-e76a-4d1e-8bbf-4a70568fee7e": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "@id": "tmp-1473919107581-14438058",
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "schema": "http://schema.org/",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#"
      },
      "type": "object",
      "title": "Kjlkjjk field schema",
      "description": "Kjlkjjk field schema autogenerated by the CEDAR Template Editor",
      "_ui": {
        "title": "kjlkjjk",
        "description": "",
        "inputType": "textfield"
      },
      "_valueConstraints": {
        "requiredValue": false
      },
      "properties": {
        "@id": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "string",
            "null"
          ]
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "_tmp": {}
      },
      "required": [
        "@value"
      ],
      "pav:createdOn": null,
      "pav:createdBy": null,
      "pav:lastUpdatedOn": null,
      "oslc:modifiedBy": null,
      "additionalProperties": false,
      "_tmp": {
        "domId": "id08609264545775526"
      }
    }
  },
  "required": [
    "@id",
    "schema:isBasedOn",
    "schema:name",
    "schema:description",
    "pav:createdOn",
    "pav:createdBy",
    "pav:lastUpdatedOn",
    "oslc:modifiedBy"
  ],
  "pav:createdOn": "2016-09-14T22:57:02-0700",
  "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
  "pav:lastUpdatedOn": "2016-09-14T22:57:02-0700",
  "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-04/schema#",
  "_tmp": {
    "domId": "id04635561151738834"
  }
}

**Comment by graybeal** [comment] 2016-09-15 06:04
Original element JSON was 
```
{
  "@id": "https://repo.metadatacenter.net/template-elements/2ddd6ffe-3db9-482c-aeb8-796767e9b0a1",
  "@type": "https://schema.metadatacenter.org/core/TemplateElement",
  "@context": {
    "pav": "http://purl.org/pav/",
    "oslc": "http://open-services.net/ns/core#"
  },
  "type": "object",
  "title": "Biocaddie dataset ish element schema",
  "description": "Biocaddie dataset ish element schema autogenerated by the CEDAR Template Editor",
  "_ui": {
    "title": "BioCADDIE Dataset Ish",
    "description": "Dataset components used by BioCADDIE",
    "order": [
      "resolvableDatasetID",
      "datasetTitle",
      "dataType"
    ]
  },
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "pav": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://purl.org/pav/"
          ]
        },
        "oslc": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://open-services.net/ns/core#"
          ]
        },
        "resolvableDatasetID": {
          "enum": [
            "https://schema.metadatacenter.net/properties/resolvableDatasetID"
          ]
        },
        "datasetTitle": {
          "enum": [
            "https://schema.metadatacenter.net/properties/datasetTitle"
          ]
        },
        "dataType": {
          "enum": [
            "https://schema.metadatacenter.net/properties/dataType"
          ]
        }
      },
      "patternProperties": {
        "^(?!pav)(?!schema)(?!oslc)[a-zA-Z][a-zA-Z0-9]*$": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "resolvableDatasetID",
        "datasetTitle",
        "dataType"
      ],
      "additionalProperties": false
    },
    "@id": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "@type": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "uniqueItems": true
        }
      ]
    },
    "pav:createdOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "pav:createdBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:lastUpdatedOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "oslc:modifiedBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "resolvableDatasetID": {
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "schema": "http://schema.org/",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#"
      },
      "type": "object",
      "title": "Resolvable dataset id field schema",
      "description": "Resolvable dataset id field schema autogenerated by the CEDAR Template Editor",
      "_ui": {
        "title": "Resolvable Dataset ID",
        "description": "",
        "inputType": "textfield"
      },
      "_valueConstraints": {
        "requiredValue": true
      },
      "properties": {
        "@id": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "string",
            "null"
          ]
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "_tmp": {
          "nested": false
        }
      },
      "required": [
        "@value"
      ],
      "pav:createdOn": "2016-09-14T22:00:46-0700",
      "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "pav:lastUpdatedOn": "2016-09-14T22:00:46-0700",
      "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "additionalProperties": false,
      "@id": "https://repo.metadatacenter.net/template-fields/71507660-0f94-4eca-88c2-7d4469f5f3a1",
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "datasetTitle": {
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "schema": "http://schema.org/",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#"
      },
      "type": "object",
      "title": "Dataset title field schema",
      "description": "Dataset title field schema autogenerated by the CEDAR Template Editor",
      "_ui": {
        "title": "Dataset Title",
        "description": "Name of the data set",
        "inputType": "textfield"
      },
      "_valueConstraints": {
        "requiredValue": false
      },
      "properties": {
        "@id": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "string",
            "null"
          ]
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "_tmp": {
          "nested": false
        }
      },
      "required": [
        "@value"
      ],
      "pav:createdOn": "2016-09-14T22:00:46-0700",
      "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "pav:lastUpdatedOn": "2016-09-14T22:00:46-0700",
      "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "additionalProperties": false,
      "@id": "https://repo.metadatacenter.net/template-fields/10860e85-0156-4f6d-9b11-9af58f1692e9",
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "dataType": {
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "schema": "http://schema.org/",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#"
      },
      "type": "object",
      "title": "Data type field schema",
      "description": "Data type field schema autogenerated by the CEDAR Template Editor",
      "_ui": {
        "title": "Data Type",
        "description": "What kind of data is represented in this dataset?",
        "inputType": "radio"
      },
      "_valueConstraints": {
        "requiredValue": false,
        "literals": [
          {
            "label": "Protein Structure"
          },
          {
            "label": "Physiological Signals"
          },
          {
            "label": "Morphology"
          },
          {
            "label": "Nucleotide Sequence"
          },
          {
            "label": "Phenotype"
          },
          {
            "label": "Clinical Trials"
          },
          {
            "label": "Proteomics Data"
          },
          {
            "label": "Gene Expression"
          },
          {
            "label": "Imaging Data"
          },
          {
            "label": "Unspecified"
          }
        ]
      },
      "properties": {
        "@id": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "array",
            "null"
          ]
        },
        "pav:createdOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "pav:createdBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "pav:lastUpdatedOn": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "oslc:modifiedBy": {
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "_tmp": {
          "nested": false
        }
      },
      "required": [
        "@value"
      ],
      "pav:createdOn": "2016-09-14T22:00:46-0700",
      "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "pav:lastUpdatedOn": "2016-09-14T22:00:46-0700",
      "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
      "additionalProperties": false,
      "@id": "https://repo.metadatacenter.net/template-fields/ce7bd634-c22c-4d4c-9c34-44d97fa60ff1",
      "$schema": "http://json-schema.org/draft-04/schema#"
    },
    "_tmp": {}
  },
  "required": [],
  "pav:createdOn": "2016-09-14T15:50:15-0700",
  "pav:createdBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
  "pav:lastUpdatedOn": "2016-09-14T22:56:47-0700",
  "oslc:modifiedBy": "https://repo.metadatacenter.net/users/1adf5ee5-cee0-47d1-9769-efbe00cdebee",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```

**Comment by martinjoconnor** [comment] 2016-09-20 01:07
Duplicate of metadatacenter/cedar-template-editor#458

**Closed** 2016-09-20 01:08 UTC
Labels: bug
