### ISSUE TITLE
"Server not responding to request"

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#485] opened 2017-06-16 20:56 UTC
Trying a search, got big error: The server is not responding to the request: "https://resource.metadatacenter.net/search?limit=100&offset=0&q=ProjectAIRR&resource_types=element,instance,template,folder&sort=-lastUpdatedOnTS"

Heh. Now will try after clearing cache...

**Comment by graybeal** [comment] 2017-06-16 20:59
Yup. Still fails.
![Screen Shot 2017-06-16 at 1.54.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f56b7191a379f1172f4f5a595ecc3c4a4356bcbbd671f3e57862804e0eeb826b5f75c66c18feea824bbc00b9208b4b84b1b4dc1fd2f42f67b6d5db1063474f4dcbed5727a39b41c95cff4ce74953a316306ae4712431.png)

**Comment by graybeal** [comment] 2017-06-16 21:04
Now is happening whenever I click on any of the filter types. And the message indicates that my search term is still in place even though I've erased it from the search field.
![Screen Shot 2017-06-16 at 2.03.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56faf7f8d928b91300aff9d1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f56b7191a37af112284f5f5b5ecc3c4a4356bcbbd671f3e57862804e0eeb826b5f75c66c18feea824bbc00b9208b4b84b1b4dc1fd2f42f67b6d5db1063474f4dcbed5727a29a48cd5bfc4ae54452a2173163ef74317b478653.png)

**Comment by graybeal** [comment] 2017-06-18 01:58
Note regarding the last comment:  If I erase the search term but do not hit return, the error still appears. If I erase the search term and hit return, the error goes away.

So, this issue seems just about searching failing. Consistently.

**Comment by martinjoconnor** [comment] 2017-08-07 20:36
Duplicate of https://github.com/metadatacenter/cedar-project/issues/498

**Closed** 2017-08-07 20:36 UTC
Labels: bug, UX
