### ISSUE TITLE
Make generic training material from Yale course material

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-project#79] opened 2016-08-04 02:01 UTC
Take:

https://docs.google.com/document/d/19GRNqz8TWxbQQB_rLoKWolAr7lB8_7owzibI0wZTaEg/edit#heading=h.e0z9tv4pv9zq

and modify to be more general purpose.

**Comment by willrett** [comment] 2016-09-15 23:37
duplicate of 87

**Closed** 2016-09-15 23:38 UTC
