### ISSUE TITLE
templates with elements cause indexing error

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#437] opened 2017-05-02 23:28 UTC
Some template which contain at least one element  get a server error when saving the metadata.  

Technical details of error

Status: 500, Internal Server Error
URL: https://resource.metadatacenter.orgx/template-instances?folder_id=https%3A%2F%2Frepo.metadatacenter.orgx%2Ffolders%2Faa810a4e-5c13-43f5-8593-2919981f9dff
Method: POST

Message: Limit of nested fields [50] in index [cedar-search-2017-05-02t11:50:25] has been exceeded
Error key: 
Exception: Limit of nested fields [50] in index [cedar-search-2017-05-02t11:50:25] has been exceeded

org.metadatacenter.server.search.elasticsearch.worker.ElasticsearchIndexingWorker -> addToIndex ( 65 )
org.metadatacenter.server.search.elasticsearch.service.ContentIndexingService -> indexNode ( 80 )
org.metadatacenter.server.search.elasticsearch.service.ContentIndexingService -> indexResource ( 44 )
org.metadatacenter.cedar.resource.resources.AbstractResourceServerResource -> createIndexResource ( 630 )
org.metadatacenter.cedar.resource.resources.AbstractResourceServerResource -> executeResourcePostByProxy ( 234 )
org.metadatacenter.cedar.resource.resources.TemplateInstancesResource -> createTemplateInstance ( 50 )
sun.reflect.NativeMethodAccessorImpl -> invoke0 ( -2 )
sun.reflect.NativeMethodAccessorImpl -> invoke ( 62 )
sun.reflect.DelegatingMethodAccessorImpl -> invoke ( 43 )
java.lang.reflect.Method -> invoke ( 497 )
org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1 -> invoke ( 81 )
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1 -> run ( 144 )
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher -> invoke ( 161 )
org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker -> doDispatch ( 160 )
org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher -> dispatch ( 99 )
org.glassfish.jersey.server.model.ResourceMethodInvoker -> invoke ( 389 )
org.glassfish.jersey.server.model.ResourceMethodInvoker -> apply ( 347 )
org.glassfish.jersey.server.model.ResourceMethodInvoker -> apply ( 102 )
org.glassfish.jersey.server.ServerRuntime$2 -> run ( 326 )
org.glassfish.jersey.internal.Errors$1 -> call ( 271 )
org.glassfish.jersey.internal.Errors$1 -> call ( 267 )
org.glassfish.jersey.internal.Errors -> process ( 315 )
org.glassfish.jersey.internal.Errors -> process ( 297 )
org.glassfish.jersey.internal.Errors -> process ( 267 )
org.glassfish.jersey.process.internal.RequestScope -> runInScope ( 317 )
org.glassfish.jersey.server.ServerRuntime -> process ( 305 )
org.glassfish.jersey.server.ApplicationHandler -> handle ( 1154 )
org.glassfish.jersey.servlet.WebComponent -> serviceImpl ( 473 )
org.glassfish.jersey.servlet.WebComponent -> service ( 427 )
org.glassfish.jersey.servlet.ServletContainer -> service ( 388 )
org.glassfish.jersey.servlet.ServletContainer -> service ( 341 )
org.glassfish.jersey.servlet.ServletContainer -> service ( 228 )
io.dropwizard.jetty.NonblockingServletHolder -> handle ( 49 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1634 )
io.dropwizard.servlets.ThreadNameFilter -> doFilter ( 34 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1621 )
io.dropwizard.jersey.filter.AllowedMethodsFilter -> handle ( 50 )
io.dropwizard.jersey.filter.AllowedMethodsFilter -> doFilter ( 44 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1621 )
org.eclipse.jetty.servlets.CrossOriginFilter -> handle ( 308 )
org.eclipse.jetty.servlets.CrossOriginFilter -> doFilter ( 262 )
org.eclipse.jetty.servlet.ServletHandler$CachedChain -> doFilter ( 1621 )
org.eclipse.jetty.servlet.ServletHandler -> doHandle ( 541 )
org.eclipse.jetty.server.handler.ScopedHandler -> nextHandle ( 188 )
org.eclipse.jetty.server.handler.ContextHandler -> doHandle ( 1239 )
org.eclipse.jetty.server.handler.ScopedHandler -> nextScope ( 168 )
org.eclipse.jetty.servlet.ServletHandler -> doScope ( 481 )
org.eclipse.jetty.server.handler.ScopedHandler -> nextScope ( 166 )
org.eclipse.jetty.server.handler.ContextHandler -> doScope ( 1141 )
org.eclipse.jetty.server.handler.ScopedHandler -> handle ( 141 )
org.eclipse.jetty.server.handler.HandlerWrapper -> handle ( 132 )
com.codahale.metrics.jetty9.InstrumentedHandler -> handle ( 241 )
io.dropwizard.jetty.RoutingHandler -> handle ( 51 )
org.eclipse.jetty.server.handler.gzip.GzipHandler -> handle ( 494 )
io.dropwizard.jetty.BiDiGzipHandler -> handle ( 68 )
org.eclipse.jetty.server.handler.RequestLogHandler -> handle ( 56 )
org.eclipse.jetty.server.handler.StatisticsHandler -> handle ( 169 )
org.eclipse.jetty.server.handler.HandlerWrapper -> handle ( 132 )
org.eclipse.jetty.server.Server -> handle ( 564 )
org.eclipse.jetty.server.HttpChannel -> handle ( 320 )
org.eclipse.jetty.server.HttpConnection -> onFillable ( 251 )
org.eclipse.jetty.io.AbstractConnection$ReadCallback -> succeeded ( 279 )
org.eclipse.jetty.io.FillInterest -> fillable ( 110 )
org.eclipse.jetty.io.ChannelEndPoint$2 -> run ( 124 )
org.eclipse.jetty.util.thread.QueuedThreadPool -> runJob ( 672 )
org.eclipse.jetty.util.thread.QueuedThreadPool$2 -> run ( 590 )
java.lang.Thread -> run ( 745 )

**Comment by martinjoconnor** [comment] 2017-05-04 17:35
Can't reproduce and may be due to old data on Debra's machine. We will monitor.

**Comment by martinjoconnor** [comment] 2017-05-15 04:02
Only seen on Debra's machine so closing.

**Closed** 2017-05-15 04:02 UTC
Labels: bug, UX
