### ISSUE TITLE
no desired metadata drop-down items

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-project#807] opened 2018-06-11 04:57 UTC
I was unable to finish the process because the system drops connection errors [reference #797] when I tried to select the Organism. Sometimes the dropdown does work but I don't see human or any other standard organism (e.g. mus musculus) available to chose from.

**Comment by graybeal** [comment] 2018-06-11 05:36
Showing all the selections is not feasible given the size of the Organism branch. We do not have any plans to fix this in the near term.

**Comment by willrett** [comment] 2018-06-12 21:45
related to #797

**Comment by martinjoconnor** [comment] 2018-06-29 20:05
This is a duplicate of above.

**Closed** 2018-06-29 20:06 UTC
Labels: duplicate
