### ISSUE TITLE
Using synonyms in addition to preferred labels

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-project#813] opened 2018-06-11 20:52 UTC
I have a field named organism and it is assigned the organism branch of NCIT.  When I search for 'homo' a match is found to the term for Human where homo is a synonym.  The list of synonyms are not returned in the call to the terminology server, so it looks like no results are found but the dropdown does not show "No Results...".

Ideally, we would populate the dropdown using the synonyms as well as the preferred name.

**Comment by willrett** [comment] 2018-06-11 22:01
![screen shot 2018-06-11 at 2 59 24 pm](https://user-images.githubusercontent.com/4739879/41259398-4c2bafda-6d88-11e8-9c34-68c8b2a4efdb.png)

**Comment by martinjoconnor** [comment] 2018-06-12 21:42
Just discussed with Debra and we will follow up with Marcos.  

There are two main options that we can think of:

(1) Don't match on synonyms. Would require flag to Terminology Server/BioPortal REST call to  signal this - if such a flag exists.

(2) List synonyms in REST call so that we can match on them.  Would require enhancement to  Terminology Server/BioPortal REST call to add this information.

**Comment by martinjoconnor** [comment] 2018-06-13 18:30
The organism branch in NCIT is used by both AIRR and CCP so we likely need to decide on an approach when Marcos returns.

**Comment by marcosmro** [comment] 2022-01-03 20:19
Duplicate of https://github.com/metadatacenter/cedar-project/issues/1160

**Closed by marcosmro** 2022-01-03 20:19 UTC
Labels: Controlled Terms
